print("Welcome to lazy")
input("Do you want you play: ")
print("ok good")
print("im lazy to code so this is the end")
input("stop going further do you agree: ")
input("ok now stop: ")
input("im getting mad: ")
input("STOP: ")
input("dont you dare: ")
input("HOW DID YOU GET THIS FAR: ")
input("im leaving: ")
input("like stop")
input("please go for a hike: ")
input("im going to eat a burger: ")
input("im going to sleep: ")
input('sleeping...: ')
input("How are you slill here?!?!?!: ")
input("i slept for an hour: ")
input("im soaking this thing in water: ")
input("oh no thats my computer: ")
input('code stopped working: ')

