word = input("Enter a sentence: ")
x = word.count("a")
y = word.count("e")
z = word.count("i")
a = word.count("o")
b = word.count("u")
space = word.count(" ")
length = len(word)
consonants = length - (x + y + z + a + b + space)
print(f"{x + y + z + a + b} vowels and {space} spaces and {consonants} consonants and {len(word)} is the length")